name: Selenium BDD Framework

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  selenium-test:

    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3. Cache Maven dependencies
      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # 4. Check Chrome
      - name: Check Chrome
        run: |
          google-chrome --version
          chromedriver --version

      # 5. Run Selenium Cucumber Tests
      - name: Run Tests
        run: |
          mvn test -Denv=qa -Dcucumber.filter.tags="@textbox"

      # 6. Upload Extent Report as GitHub Actions Artifact
      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport
          path: target/ExtentReport/

      # 7. Prepare report for GitHub Pages
      - name: Prepare GitHub Pages Report
        if: always()
        run: |
          mkdir -p pages
          cp -r target/ExtentReport/* pages/

      # 8. Upload report to GitHub Pages
      - name: Upload Pages Artifact
        if: always()
        uses: actions/upload-pages-artifact@v4
        with:
          path: pages/


  deploy:

    if: always()
    needs: selenium-test

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      # 9. Deploy report to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4